from .scripts.image import IMAGE_CLASS_MAPPINGS, IMAGE_DISPLAY_NAME_MAPPINGS
from .scripts.mask import MASK_CLASS_MAPPINGS, MASK_DISPLAY_NAME_MAPPINGS
from .scripts.preview import PREVIEW_CLASS_MAPPINGS, PREVIEW_DISPLAY_NAME_MAPPINGS
from .scripts.primitive import PRIMITIVE_CLASS_MAPPINGS, PRIMITIVE_DISPLAY_NAME_MAPPINGS
from .scripts.switch import SWITCH_CLASS_MAPPINGS, SWITCH_DISPLAY_NAME_MAPPINGS
from .scripts.utility import UTILITY_CLASS_MAPPINGS, UTILITY_DISPLAY_NAME_MAPPINGS

WEB_DIRECTORY = "./web"

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(IMAGE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(IMAGE_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(MASK_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MASK_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(PREVIEW_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PREVIEW_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(PRIMITIVE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(PRIMITIVE_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(SWITCH_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(SWITCH_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(UTILITY_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(UTILITY_DISPLAY_NAME_MAPPINGS)

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY"
]
